### ISSUE TITLE
Greylist repositories - instead of blacklisting

### ISSUE THREAD

**Issue by superbilk** [andygrunwald/TrendingGithub#5]
Greylist previously tweeted repositories for 1/2/3 months instead of blacklisting. That way they will reappear if they are trending again.

**Comment by andygrunwald** [comment]
Nice idea!
I think 1 month is enough, because the "max" time limit is monthly at github.com/trending

**Comment by andygrunwald** [comment]
I switched the blacklisting to a grey listing for 45 days. Thanks for your input @superbilk!
